export const PLANS= {
    free:{
        id:"free",
        name:"Free",
        amount:0,
        credits:100,
        validity:30,
    },
      starter:{
        id:"starter",
        name:"starter",
        amount:199,
        credits:500,
        validity:30,
    },
      pro:{
        id:"pro",
        name:"pro",
        amount:499,
        credits:1000,
        validity:30,
    }
}