import pptxgen from "pptxgenjs";

const COLORS = {
    primary: "2563EB",
    secondary: "0F172A",
    text: "334155",
    light: "F8FAFC",
    border: "E2E8F0",
    white: "FFFFFF",
    muted: "64748B",
};

export const generatePPT = async (data) => {
    const ppt = new pptxgen();

    // Presentation settings
    ppt.layout = "LAYOUT_WIDE";
    ppt.author = "CortexAI";
    ppt.title = data.title || "Presentation";
    ppt.subject = data.title || "Generated by CortexAI";
    ppt.company = "CortexAI";

    ppt.theme = {
        headFontFace: "Aptos",
        bodyFontFace: "Aptos",
    };

    // Cover slide
    addCover(ppt, data);

    // Content slides
    data?.slides?.forEach((slideData, index) => {
        addContentSlide(
            ppt,
            slideData.title,
            slideData.points,
            index + 1,
            data.slides.length
        );
    });

    // Thank you slide
    addThankYou(ppt);

    return ppt;
};


// ===============================
// Content Slide
// ===============================

const addContentSlide = (ppt, title, points = [], page, total) => {
    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.white,
    };

    // Title
    slide.addText(title || "Untitled Slide", {
        x: 0.6,
        y: 0.35,
        w: 12,
        h: 0.4,
        align: "center",
        bold: true,
        color: COLORS.primary,
        fontSize: 24,
    });

    // Divider
    slide.addShape(ppt.ShapeType.line, {
        x: 0.6,
        y: 0.85,
        w: 12,
        h: 0,
        line: {
            color: COLORS.border,
            width: 1.2,
        },
    });

    // Maximum 6 points
    const visiblePoints = points.slice(0, 6);

    visiblePoints.forEach((point, index) => {
        const y = 1.2 + index * 0.75;

        // Point container
        slide.addShape(ppt.ShapeType.roundRect, {
            x: 0.7,
            y,
            w: 12,
            h: 0.58,
            fill: {
                color: page % 2 ? "F8FAFC" : "EFF6FF",
            },
            line: {
                color: COLORS.border,
                width: 1,
            },
        });

        // Bullet circle
        slide.addShape(ppt.ShapeType.ellipse, {
            x: 0.92,
            y: y + 0.18,
            w: 0.12,
            h: 0.12,
            fill: {
                color: COLORS.primary,
            },
            line: {
                color: COLORS.primary,
            },
        });

        // Point text
        slide.addText(String(point || ""), {
            x: 1.2,
            y: y + 0.08,
            w: 11,
            h: 0.35,
            color: COLORS.text,
            fontSize: 15,
            fit: "shrink",
            margin: 0,
        });
    });

    // Footer page number
    slide.addText(`${page}/${total}`, {
        x: 11.8,
        y: 6.9,
        w: 0.8,
        h: 0.2,
        align: "right",
        color: COLORS.muted,
        fontSize: 10,
        margin: 0,
    });

    // Footer brand
    slide.addText("CortexAI", {
        x: 0.6,
        y: 6.9,
        w: 2,
        h: 0.2,
        align: "left",
        color: COLORS.muted,
        fontSize: 10,
        margin: 0,
    });
};


// ===============================
// Cover Slide
// ===============================

const addCover = (ppt, data) => {
    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.primary,
    };

    // Top accent bar
    slide.addShape(ppt.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.33,
        h: 0.18,
        fill: {
            color: "60A5FA",
        },
        line: {
            color: "60A5FA",
        },
    });

    // Title
    slide.addText(data.title || "Presentation", {
        x: 0.7,
        y: 1.7,
        w: 12,
        h: 0.8,
        align: "center",
        color: COLORS.white,
        bold: true,
        fontSize: 28,
        fit: "shrink",
    });

    // Subtitle
    slide.addText(data.subtitle || "", {
        x: 1,
        y: 2.8,
        w: 11.5,
        h: 0.5,
        align: "center",
        color: "DBEAFE",
        fontSize: 20,
        fit: "shrink",
    });

    // Footer
    slide.addText("Generated by CortexAI", {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align: "center",
        color: "BFDBFE",
        fontSize: 10,
        margin: 0,
    });
};


// ===============================
// Thank You Slide
// ===============================

const addThankYou = (ppt) => {
    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.secondary,
    };

    // Thank You
    slide.addText("Thank You", {
        x: 0,
        y: 2.2,
        w: 13.33,
        h: 0.8,
        align: "center",
        color: COLORS.white,
        fontSize: 34,
        bold: true,
    });

    // Footer
    slide.addText("Generated by CortexAI", {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align: "center",
        color: "94A3B8",
        fontSize: 10,
        margin: 0,
    });
};