// import PDFDocument from 'pdfkit';

// export const generatePDF = async (data) => {
//     return new Promise((resolve, reject) => {
//         const doc = new PDFDocument({
//             size: "A4",
//             margin: 50,
//             info: {
//                 Author: "CortexAi",
//                 Title: data.title,
//                 Creator: "CortexAi",
//             }
//         });
//         const chunks = []
//         doc.on("data", (chunk) => {
//             chunks.push(chunk);
//         })
//         doc.on("end", () => resolve(Buffer.concat(chunks)))
//         doc.on("error", () => reject);

//         // title
//         doc
//             .fontSize(28)
//             .text(data.title, {
//                 align: "center"  
//             })
//             .fillColor("#111827")


//         if (data.subtitle) {
//             doc.moveDown(0.5)
//         }


//         // subtitle
//         doc
//             .fontSize(12)
//             .text(data.subtitle, {
//                 align: "center"
//             })
//             .fillColor("#6B7280")


//         doc.moveDown(2)

//         //sections

//         data?.sections?.forEach(s => {
//             doc
//                 .fontSize(18)
//                 .text(s.heading, {
//                     align: "center"
//                 })
//                 .fillColor("#111827")


//             doc.moveDown(0.5)

//             //points

//             s?.points?.forEach(p => {

//                 doc
//                     .fontSize(12)
//                     .text("• " + p, {
//                         lineGap: 5,
//                     })
//                     .fillColor("#374151")
//             })
//             doc.moveDown()

//         })

//         doc.moveDown()


//         //footer
//         doc
//             .fontSize(10)
//             .text("Generated by CortexAi", {
//                 align: "center"
//             })
//             .fillColor("#9CA3AF")


//         doc.end()

//     })

// }
import PDFDocument from 'pdfkit';

export const generatePDF = async (data) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({
            size: 'A4',
            margin: 50,
            info: {
                Author: 'CortexAi',
                Title: data.title || 'Document',
                Creator: 'CortexAi',
            }
        });

        const chunks = [];
        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject); // Corrected error handler

        // 1. Title
        doc.font('Helvetica-Bold')
            .fontSize(24)
            .fillColor('#111827')
            .text(data.title || 'Document', { align: 'center' });

        // 2. Subtitle
        if (data.subtitle) {
            doc.moveDown(0.4)
                .font('Helvetica')
                .fontSize(12)
                .fillColor('#6B7280')
                .text(data.subtitle, { align: 'center', lineGap: 3 });
        }

        doc.moveDown(1.5);

        // 3. Sections
        data?.sections?.forEach((s) => {
            // Section Header
            doc.font('Helvetica-Bold')
                .fontSize(15)
                .fillColor('#1E293B')
                .text(s.heading, { align: 'left' });

            doc.moveDown(0.4);

            // Points
            s?.points?.forEach((p) => {
                doc.font('Helvetica')
                    .fontSize(11)
                    .fillColor('#374151')
                    .text(`•  ${p}`, {
                        indent: 10,
                        lineGap: 4
                    });
            });

            doc.moveDown(0.8);
        });

        // 4. Footer
        doc.moveDown(1.5)
            .font('Helvetica')
            .fontSize(9)
            .fillColor('#9CA3AF')
            .text('Generated by CortexAi', { align: 'center' });

        doc.end();
    });
};